basic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('infra.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

infra/urls.py
from django.urls import path
from infra.views import DemoList, DemoDetail
from . import views

app_name='infra'

urlpatterns = [
    
    path('', DemoList.as_view(), name='demo_list'),
    path('<int:pk>', DemoDetail.as_view(), name='demo_detail'),
    path('about',views.about, name='about'),
    path('project', views.project, name='project'),
    path('contact', views.contact, name='contact'),



]

infra/models.py
from django.db import models

# Create your models here.

class Demo(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='images')
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.title





        

infra/views.py
from django.shortcuts import render


# Create your views here.
from infra.models import Demo
from django.views.generic import DetailView, ListView
from django.http import HttpResponse
from django.views.decorators.http import require_http_methods

@require_http_methods(["GET"])
def about(request):
    
    return render(request, 'about.html')

@require_http_methods(["GET"])
def project(request):
    return render(request, 'project.html')

@require_http_methods(["GET"])
def contact(request):
    return render(request, 'contact.html')
   

class DemoList(ListView):
    
    model = Demo
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    pass

class DemoDetail(DetailView):
    model = Demo

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    pass

infra/templates/infra/demo_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


</head>

<body>

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column" style="background: rgba(128, 128, 128, 0.548);">
        <h2 class="brand"> <a class="nav-link active" style="color: black;" href="{% url 'infra:demo_list' %}"> Zeus Infra </a> </h2>
        <nav class="nav  justify-content-end">
                <a class="nav-link active " style="color:black;" href="{% url 'infra:demo_list' %}">Home</a>
                <a class="nav-link active" style="color:black;" href="{% url 'infra:about' %}">About Us</a>
                <a class="nav-link active" style="color:black;" href="{% url 'infra:project' %}">Projects</a>
                <a class="nav-link active" style="color:black;" href="{% url 'infra:contact' %}">Contact Us</a>
              </nav>
    </div>
    
    
    
    
    
    <div class="col-md-12">
    
    
        <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <h2 class="card-title font-weight-bolder">{{object.title}}</h2>
                <strong class="d-inline-block mb-2 text-primary">Mumbai</strong>
                <h4 class="mb-0">Description</h4>
                
                <p class="card-text mb-auto">{{object.description}}</p>
                <p class="card-text mb-auto font-weight-bold">Price: {{object.price}} Cr. &#x20B9</p>
            </div>
            <div class="col-auto d-none d-lg-block">
                <img src="{{ object.image.url}}" class="img-fluid" alt="Responsive image">
            </div>
        </div>
    </div>


















        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>

</html>

infra/templates/infra/demo_list.html
{% extends "home.html" %}

{% block body %}


<div class="album py-5 bg-light back">
    <div class="container ">

        <div class="row">
            {% for asset in object_list %}
            <div class="col-md-4 ">

                <div class="card mb-4 shadow-sm" style="float:right">
                    <a href="{% url 'infra:demo_detail' asset.pk %}">
                    <img src="{{asset.image.url}}" class="card-img-top" height="400px" alt="...">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title font-weight-bolder">{{asset.title}}</h5>
                        <p class="card-text">{{asset.description}}</p>
                    </div>

                    <div class="card-body">
                        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to
                            additional content. This content is a little bit longer.</p>

                    </div>
                </div>

            </div>
            {% endfor %}
        </div>

    </div>
</div>


<nav aria-label="Page navigation example">
    <ul class="pagination">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% endif %}
<!--       
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
--> 
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number  }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
        {% endif %}
    </ul>
</nav>




{% endblock body %}

templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Zeus Infra</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>

    
    .shape{
        background: rgba(0, 0, 0, 0.63);
        
    }

    .tile{
        margin-top: 10px;
    }
    #para{
        color: white;
        margin-top: 60px;
    }




</style>


</head>
<body>
    


    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column" style="background: rgba(92, 91, 91, 0.836);">
        <h2 class="brand"> <a class="nav-link active" style="color: black;" href="{% url 'infra:demo_list' %}"> Zeus Infra </a> </h2>
        <nav class="nav  justify-content-end">
                <a class="nav-link active " style="color:white;" href="{% url 'infra:demo_list' %}">Home</a>
                <a class="nav-link active" style="color:white;" href="{% url 'infra:about' %}">About Us</a>
                <a class="nav-link active" style="color:white;" href="{% url 'infra:project' %}">Projects</a>
                <a class="nav-link active" style="color:white;" href="{% url 'infra:contact' %}">Contact Us</a>
              </nav>
    </div>
    
    <div class="container-fluid back">
        <div class="row align-items-center shape">
            <div class="col-md-4 align-self-start">
    
                <h2 class="font-weight-bolder tile" style="color: white;">About Zeus Infra</h2>
    
                <div class="card" style="width: 18rem;">
                        <img src="{% static 'img/external.jpg' %}" class="card-img-top" alt="...">
                        <div class="card-body">
                          <h5 class="card-title">Mumbai</h5>
                          
                        </div>
                      </div>

            </div>
            <div class="col-md-8">
                <div>
    
                    <p id="para">
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptates molestias odit doloremque esse
                        nihil rem assumenda cumque cum officia. Ipsa numquam dolores eaque debitis, error necessitatibus
                        veniam quia eos atque!
                    </p>
    
    
                </div>
    
            </div>
        </div>

















    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Zeus Infra</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style>
    body{
        background: rgba(2, 129, 123, 0.651);
    }
    .pad{
        margin-top: 20px;
        margin-left: 40px;
    }


</style>

</head>
<body>
    

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column" style="background: rgba(128, 128, 128, 0.548);">
        <h2 class="brand"> <a class="nav-link active" style="color: black;" href="{% url 'infra:demo_list' %}"> Zeus Infra </a> </h2>
        <nav class="nav  justify-content-end">
                <a class="nav-link active " style="color:black;" href="{% url 'infra:demo_list' %}">Home</a>
                <a class="nav-link active" style="color:black;" href="{% url 'infra:about' %}">About Us</a>
                <a class="nav-link active" style="color:black;" href="{% url 'infra:project' %}">Projects</a>
                <a class="nav-link active" style="color:black;" href="{% url 'infra:contact' %}">Contact Us</a>
              </nav>
    </div>
    


<div class="container-fluid">
    <div class="row ">
        <div class="col-md-4 pad">
            <h3>Contact Us:</h3>
            <h5>Mumbai Office:</h5>
            <p>Lorem ipsum dolor sit, amet consectetur 
                ex, odit libero optio officia repellendus
                nesciunt omnis eveniet aut mollitia temporibus
                sit, reprehenderit ipsum. Quod molestias veniam corrupti.
                <strong>Mumabi:400031</strong>
            </p>

            <h3>Devploved By</h3>
            <p><strong>Ajay Suryawanshi</strong></p>
            






        </div>









    </div>








</div>



















    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Zeus Infra</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      body{
        background: linear-gradient(rgba(0, 0, 0, 0.534),rgba(128, 128, 128, 0.192));
      }
      .back{
        background-image: url("static/img/construction.jpg");
        width: 100%;
        height: auto;
      }
            .bd-placeholder-img {
              font-size: 1.125rem;
              text-anchor: middle;
              -webkit-user-select: none;
              -moz-user-select: none;
              -ms-user-select: none;
              user-select: none;
            }
      
            @media (min-width: 768px) {
              .bd-placeholder-img-lg {
                font-size: 3.5rem;
              }
            }
          </style>
          <!-- Custom styles for this template -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet">

</head>
<body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand"> <a class="active" style="text-decoration: none; color: black;" href="{% url 'infra:demo_list' %}"> Zeus Infra </a></h3>
      <nav class="nav nav-masthead justify-content-center">
        <a class="nav-link active " style="color:white;" href="{% url 'infra:demo_list' %}">Home</a>
        <a class="nav-link active" style="color:white;" href="{% url 'infra:about' %}">About Us</a>
        <a class="nav-link active" style="color:white;" href="{% url 'infra:project' %}">Projects</a>
        <a class="nav-link active" style="color:white;" href="{% url 'infra:contact' %}">Contact Us</a>
      </nav>
    </div>
  </header>

  <div id="carouselExampleFade" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'img/building1.jpg' %}" class="d-block w-100" height="450px" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/building2.jpg' %}" class="d-block w-100" height="450px" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/Amazing-3.jpg' %}" class="d-block w-100" height="450px" alt="...">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    
      {% block body %}

      {% endblock body %}
  
      

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Developed By <strong>Ajay S.</strong>  </p>
    </div>
  </footer>
    </div>

    







    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>